server:
  port: 8082
  servlet:
    context-path: /
    encoding:
      force-response: true
  tomcat:
    uri-encoding: utf-8

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/starshop_test?useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root123
  jpa:
    open_in_view: false
    show_sql: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
      USE_BIG_DECIMAL_FOR_FLOATS: true
wx:
  miniapp:
    configs:
      - appid: wxaa0eca4be4ff2b3c
        secret: 630bc05d83d22cded090fcc0dfa0acc1
        token: #微信小程序消息服务器配置的token
        aesKey: #微信小程序消息服务器配置的EncodingAESKey
        msgDataFormat: JSON
logging:
  level:
    root: warn
    org.springframework.web: info
    cn.binarywang.wx.miniapp: debug
    com.stardata.starshop2: trace
  pattern:
    console: '%p%m%n'

