apiVersion: apps/v1
kind: Deployment
metadata:
  name: starshop-ddd-demo
  labels:
    app: starshop-ddd-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: starshop-ddd-demo
  template:
    metadata:
      labels:
        app: starshop-ddd-demo
    spec:
      containers:
        - name: eurekaserver
          image: ccr.ccs.tencentyun.com/default-ns/starshop-eureka:0.0.7
          ports:
            - containerPort: 7771
        - name: gateway
          image: ccr.ccs.tencentyun.com/default-ns/starshop-gateway:0.0.7
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-javaagent:/otel-agent.jar -Dotel.jmx.target.system=tomcat -Dotel.resource.attributes=service.name=starshop_gateway -Dotel.exporter.otlp.endpoint=http://smartobserv-collector.smartobserv-dev:4317"
          ports:
            - containerPort: 80
        - name: authapp
          image: ccr.ccs.tencentyun.com/default-ns/starshop-auth:0.0.7
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-javaagent:/otel-agent.jar -Dotel.jmx.target.system=tomcat -Dotel.resource.attributes=service.name=starshop_authapp -Dotel.exporter.otlp.endpoint=http://smartobserv-collector.smartobserv-dev:4317 --spring.main.allow-bean-definition-overriding=true"
            - name: MYSQL_SERVER
              value: smartobserv-mysql.smartobserv-dev
            - name: MYSQL_PORT
              value: '3306'
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              value: password
          ports:
            - containerPort: 8080
        - name: simu-orderapp
          image: ccr.ccs.tencentyun.com/default-ns/starshop-simuorder:0.0.7
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-javaagent:/otel-agent.jar -Dotel.jmx.target.system=tomcat -Dotel.resource.attributes=service.name=starshop_simuorder -Dotel.exporter.otlp.endpoint=http://smartobserv-collector.smartobserv-dev:4317 --spring.main.allow-bean-definition-overriding=true"
            - name: MYSQL_SERVER
              value: smartobserv-mysql.smartobserv-dev
            - name: MYSQL_PORT
              value: '3306'
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              value: password
            - name: BOOTSTRAP_SERVER
              value: 106.52.170.200:19092
          ports:
            - containerPort: 7081
        - name: productapp
          image: cr.ccs.tencentyun.com/default-ns/starshop-product:0.0.7
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-javaagent:/otel-agent.jar -Dotel.jmx.target.system=tomcat -Dotel.resource.attributes=service.name=starshop_productapp -Dotel.exporter.otlp.endpoint=http://smartobserv-collector.smartobserv-dev:4317 --spring.main.allow-bean-definition-overriding=true"
            - name: MYSQL_SERVER
              value: smartobserv-mysql.smartobserv-dev
            - name: MYSQL_PORT
              value: '3306'
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              value: password
          ports:
            - containerPort: 7082
        - name: customerapp
          image: ccr.ccs.tencentyun.com/default-ns/starshop-customer:0.0.7
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-javaagent:/otel-agent.jar -Dotel.jmx.target.system=tomcat -Dotel.resource.attributes=service.name=starshop_customerapp -Dotel.exporter.otlp.endpoint=http://smartobserv-collector.smartobserv-dev:4317 --spring.main.allow-bean-definition-overriding=true"
            - name: MYSQL_SERVER
              value: smartobserv-mysql.smartobserv-dev
            - name: MYSQL_PORT
              value: '3306'
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              value: password
            - name: REDIS_SERVER
              value: smartobserv-redis.smartobserv-dev
            - name: REDIS_PORT
              value: '6379'
            - name: REDIS_USER
              value: root
            - name: REDIS_PASSWORD
              value: ''
          ports:
            - containerPort: 7083
        - name: platform-integration-app
          image: ccr.ccs.tencentyun.com/default-ns/starshop-platint:0.0.7
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-javaagent:/otel-agent.jar -Dotel.jmx.target.system=tomcat -Dotel.resource.attributes=service.name=starshop_platform-integration -Dotel.exporter.otlp.endpoint=http://smartobserv-collector.smartobserv-dev:4317 --spring.main.allow-bean-definition-overriding=true"
            - name: MYSQL_SERVER
              value: smartobserv-mysql.smartobserv-dev
            - name: MYSQL_PORT
              value: '3306'
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              value: password
            - name: BOOTSTRAP_SERVER
              value: 106.52.170.200:19092
          ports:
            - containerPort: 7081
        - name: load-generator
          image: ccr.ccs.tencentyun.com/default-ns/starshop-load-generator:0.0.6
          ports:
            - containerPort: 7089

---
apiVersion: v1
kind: Service
metadata:
  name: starshop-ddd-demo
  labels:
    app: starshop-ddd-demo
spec:
  ports:
    - name: gateway
      port: 80
      targetPort: 80
    - name: eureka
      port: 7771
      targetPort: 7771
    - name: auth
      port: 7080
      targetPort: 7080
    - name: order
      port: 7081
      targetPort: 7081
    - name: product
      port: 7082
      targetPort: 7082
    - name: customer
      port: 7083
      targetPort: 7083
    - name: loadgenerator
      port: 7089
      targetPort: 7089
  selector:
    app: starshop-ddd-demo
  type: ClusterIP
