#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


### gateway proxy getUserInfo
GET http://localhost/v2/users/1
Accept: application/json
Content-Type: application/json

### gateway proxy customer by_user
GET http://localhost/v2/shops/1/customers/by_user?userId=1
Accept: application/json
Content-Type: application/json

### gateway proxy product detail
GET http://localhost/v2/products/1
Accept: application/json
Content-Type: application/json

### gateway proxy wxLogin
POST http://localhost/v2/auth/wxlogin
Accept: application/json
Content-Type: application/json

{
"code": "081sloll28T8d94nl8nl2hxKhh3slolv",
"rawData": "{\"nickName\":\"深清秋\",\"gender\":0,\"language\":\"zh_CN\",\"city\":\"\",\"province\":\"\",\"country\":\"\",\"avatarUrl\":\"https://thirdwx.qlogo.cn/mmopen/vi_32/Q0j4TwGTfTKq2CRmib1mpu4hOFYtcIHgAmS7DicCEfYkUHoPmPQn74BXH5GerjoMOxIqib7iafNNBw2ZAicBj6gZGUQ/132\"}",
"signature": "06846a4ba8b003af5d98fadfaf376a652e5d75d7"
}

### gateway proxy post order
POST http://localhost/v2/shops/1/orders?userId=1
Accept: application/json
Content-Type: application/json

{"items":[{"productId":1, "count":3},{"productId":2, "count":2},{"productId":3, "count":12}]}
